const blue = [
  {
    ARTIST: "Sigur Rós",
    LINK: "https://youtu.be/n-BjxCpmxmo",
    ID: "n-BjxCpmxmo",
    COMMENT: "This concert is like a drug for me.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I like to divide musical groups into two basic categories: A. Sigur Ros B. The other bands",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This concert has repaired my DNA.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Music and art will save our souls.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'm pretty sure Staralfur is the best song ever written",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "life is too short",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Just imagine if they played Varúð  with orchestra... That must be magical",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Every time I listen to À... I can't breathe. It's so beautiful!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is just magnificent: I have no words.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Just incredible. I can't find the words to adequately express how I feel.",
    "": "",
  },
  {
    ARTIST: "Rudimental",
    LINK: "https://youtu.be/5hw77PAxlUk",
    ID: "5hw77PAxlUk",
    COMMENT: "Anne Marie the best I love Anne Marie",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love anne-marie and sinead harnett",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "mucho flow!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best Rudimental performance",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "feel the love",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing! Innovative and epic.Great job!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"...as always, one of the best vibes are made in UK!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They are awesome",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "that little dance",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "right here",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/6m7XWVIYqTs",
    ID: "6m7XWVIYqTs",
    COMMENT: "Sounds engineer needed",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Rudimental <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "LIKE FOR MORE HOZIEER!!!  BY THE WAY IM BUZZ LIGHTHEAR...!!! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Will hearddddd",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Will Heard!! <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Absolute GODS! Love them all :)",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "So amazing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "What a classic!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "realy realy gooood song",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i love rudimental ❤",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/6XjATefHBjI",
    ID: "6XjATefHBjI",
    COMMENT: "That drummer rules!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Ella Eyre got the best vocals from the vocalists, imo, she sings so heart-warming yet spine-shiver-crawlingly! <3 and makes it look so easy"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the trumpet player is awesome",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The drummer and the bloke on trumpet are both fire!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Why is Ella not their lead singer......,i just don\'t gettit :-("',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the song name is: SOLO",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Fantástico!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love Ella",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I LOVE THEM!!! YOU ARE AMAZING GUYS! <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Loveloveloveeeeeeeeeee this",
    "": "",
  },
  {
    ARTIST: "AIR",
    LINK: "https://youtu.be/ZP9SvddHdO0",
    ID: "ZP9SvddHdO0",
    COMMENT: "This is the best concert in my life so far.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"What a band. They are amazing. When someone tells me that electronic music is not good, I tell them to listen to AIR."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Amazing concert. So pure, so simple."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"I am an air fan since 1998, one of my favorite bands ever."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "There's nothing like AIR.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Music is a language in what it speaks to us, we ""understand"" something even if we don\'t know what. Thanks Air to give us these beautiful tones ;)"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Sounding that good is supernatural. There are exceptional sound guys working behind the band.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Absolut fantastic! The soul of old and new synths in perfect combination.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"This is magic, it's magic...music is the only language all people do understand. La Femme d'Argent is wonderful\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"what a great and potent version of ""how does it make you feel?"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/3GALJl6Y16w",
    ID: "3GALJl6Y16w",
    COMMENT: "Air fans are type of people that i would be friends with",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "We need a new album ASAP !!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Beautiful concert. Unfortunately the architect\'s name is not Niedemeyer, but Niemeyer. Cheers!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "If anyone can work those old vintage analogue's it's these boys. Great stuff guys.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I'd forgotten just how much I love Air.....what a class act they are!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The opening of Cherry Blossom Girl just made me almost cry!! The lights!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "whoever did the lighting and the building it was perfect. the inside resembles a magnetic field. the reciprocating hyperbaloid",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The angels went back down to earth from space.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"It is such an honor...to be a fan of this group and their music. Thank you, AIR."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/-XSSQGfIV8A",
    ID: "-XSSQGfIV8A",
    COMMENT: "Absolutely fantastic!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of my favorites bands of all time!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Magnificent !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Great concert.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "An absolutely perfect set and  performance.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "GREAT song",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Stunning",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "cool",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Fabulous.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "nothing but hot air",
    "": "",
  },
  {
    ARTIST: "Chet Faker",
    LINK: "https://youtu.be/8PIr3SToDVM",
    ID: "8PIr3SToDVM",
    COMMENT: "Chet's got some nice dance moves right there!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"they didnt give a damn still on their phones lol, i can say chet faker is one of my favorite musicians such an amazing talent"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Yes! His voice is heavenly",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i swear the rest of the band just teleports on and off...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"so great. super cool seeing him with an audience this large, he rocks it"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "When cigarettes and chocolate drops...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "thousand likes to his performance. love it love it.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "And Talk is cheap",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "bravo bravooooooo",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "why are none of my favorite chet faker songs on spotify wtf",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/veCnQve0rqc",
    ID: "veCnQve0rqc",
    COMMENT: "This is good but I thought he was much funnier in The Hangover.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "this guy has serious talent. multitasking all that live is real.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I really like this guy. Glad to have found some newer artists with flavour. <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "When you play a song for the first time and it's 1998... art in a few minutes",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "DAMN ! NO DIGGITY Killed",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "he's so hot it makes me cry",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "legit chill...love his soul style",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I give him props!! LIVE AUDIO AND VOCALS! This guy is talented!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This guy is so fk'ng talented",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is just perfection",
    "": "",
  },
  {
    ARTIST: "Anderson .Paak",
    LINK: "https://youtu.be/pCDJv4WQ_bc",
    ID: "pCDJv4WQ_bc",
    COMMENT: '"Mark my words, Anderson .Paak will be a legend."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"He will go down in history. He doesn\'t just appeal to R&B fans, or hip-hop fans... he appeals to fans of ANY MUSIC."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wheres that dope keyboard player of his? He is missed here.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Prince is looking down on this dude smiling forreal",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"This is that 70s funk soul shit, love it."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I need to hear .Paak and 3000.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "YES LAWD",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Want .Paak to become a legend",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That one dude screaming the lyrics is dedicated.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the kendrick lamar of soul",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/tLYwPSz-MJ4",
    ID: "tLYwPSz-MJ4",
    COMMENT:
      "Anderson is a genius of our time and isn't receiving the attention he deserves. No one compares with him and wont for a long time",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "He is so unbelievably talent overall you can’t help but just admire his performances... go watch his tiny desk",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"The entire set, band and background singers included, was incredible"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One white boy in the back say he know how to two-step",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "RIP KOBE RIP MAC",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Love the Kobe tribute #8",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "How is this crowd so dead... saw him live and he’s one of the best shows I’ve ever seen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He plays drums?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Yessirrr",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Who are the girls in the back",
    "": "",
  },
  {
    ARTIST: "Anne-Marie",
    LINK: "https://youtu.be/TDB578_bNJE",
    ID: "TDB578_bNJE",
    COMMENT: "Anne Marie fans❤❤",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I love the way she screams. It doesn\'t hurt and it fits, enough pitch, enough thinness. Waah, her voice is so unique."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"She\'s the happiest singer on the stage ever, i love her positive vibe"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"She is born to be a performer. No back up dancers nor dance steps needed, just unbreakable connection with audience! ❤ you Anne Marie!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She's a fan of her own. And that's a beautiful sight.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"She\'s pure talent, she slays either live or in recording."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Flawless She is so talented!!! Love her and her voice",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Anne Marie is one of the few artists who can really put a show on. Like literally",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "this queen did not even need backup dancers",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is one of the most genuine concert i've ever watched! She's a gem!",
    "": "",
  },
  {
    ARTIST: "Ed Sheeran",
    LINK: "https://youtu.be/223eI1x6PsQ",
    ID: "223eI1x6PsQ",
    COMMENT: '"Talented beyond words, who doesn\'t he touch A great artist "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "He's rocking the crowd with just his voice and his solo guitar.. He is truly a legend legend Singer.....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I love how ed sheeran only uses his looper instead of having a band with him. Hes just truly amazing and such a humble performer.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Finally someone who sounds just as good live as recorded",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"Can't get enough of Ed,he's so talented. He reminds me of my son whose a musician too.\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Just love Ed Sheeran Love all his music so talented",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Just have to love this Guy, such a beautiful soul in an imperfect reality..."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "That medley was everything! It's so nostalgic to hear him sing Drunk.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I really hope he is enjoying his break right now, he deserves it"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Awe, my favorite artist."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/05272IrStv4",
    ID: "05272IrStv4",
    COMMENT: "This is talent guys! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"He doesn’t need need a band, he doesn’t need to dance, he doesn’t need to do anything else to be a perfect artist."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "He’s perfect like this! Doing everything with just a guitar. This incredible!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love Ed Sheeran!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This performance is so smooth. I can\'t believe this is all live, nothing is pre recorded, he and himself as a one man band."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Bloodstream is so underrated",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "this guy is a one-man band all he need is his guitar and his loop pad",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I listen to him every day! I love so much!❤❤",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Someone proposed during the song <Perfect>",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Who else is lovin that older woman in the front, bobbin her head to the beat? Awesome!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/lR3vIjAZDnM",
    ID: "lR3vIjAZDnM",
    COMMENT:
      '"Does anyone else not find it crazy that this whole concert is him, his guitar, and a loop pedal?"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That shows that he is one of the greatest musicians of our time.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "ED Sheeran is precious and needs to be protected at all costs",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Ed is my daughter\'s hero, she wants to be just like him when she grows up. I see why."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "i watched the whole video and guess what? i didnt waste a single second of life",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "HOLY JESUS ED IS AWESOMEEEEEEEEEEEEEEEEE!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"He\'s a one man band, and he is a genius for sure."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is like the only artist that sounds the same as live and in the recorded songs.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "i honestly believe he is one of the few artists who sound even better live",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Almost 2 hours,  singing and playing by himself.  Absolutely legend.  "',
    "": "",
  },
  {
    ARTIST: "Tracy Chapman",
    LINK: "https://youtu.be/kUXahDmsVdU",
    ID: "kUXahDmsVdU",
    COMMENT:
      "She is my angel baby. I wish i could hug her for 10 mins straight.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is one of those songs that seems like has existed from all eternity",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Such a voice comes once in a century. So unique and touchy.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "First heard this talented lady in concert opening for Bob Dylan about 30 years ago. I was blown away. Still am. Timeless.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Thank you, Tracy, for sharing your artistic gifts. Your voice brings me comfort and smiles."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The best acoustic solo performance in history of popular music.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Tracy is the best",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "So pure and clean music.  A  guitar and her voice is all that was needed to make great music.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I love Tracy with my whole life!! Her songs have been a source of inspiration to me..",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Very Real . Thank you Tracy .",
    "": "",
  },
  {
    ARTIST: "Simon & Garfunkel",
    LINK: "https://youtu.be/Bxryb3xN-Lo",
    ID: "Bxryb3xN-Lo",
    COMMENT:
      "So sad that there was no connection to each other on the concert. They made beautiful songs.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "And who is so not interested came with a solo guitar in The Sound of Silence?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "ART VOICE is so Cool as ICE..",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"These song has only four guitar key...Dm, C, Bb and  F"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Thank you, Simon. Thank you, Garfunkel. Its An everlasting Joy."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Bridge over troubled water is my all time favourite since I was 9",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Beautifully done. Arts voice is magical..",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Yester years were great when music was really music. I just dont get tired listening to S&G especially on a long drive.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I got lots of memories with their songs, paul simon is the reason why i learned to play guitar. Quality Music"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Quiet just listen !",
    "": "",
  },
  {
    ARTIST: "Marcus Miller",
    LINK: "https://youtu.be/J2VL0uqZP18",
    ID: "J2VL0uqZP18",
    COMMENT:
      "One of the hardest jazz and base players of all time he is I'm telling you. Big up Marcus miller always I'm a huge fan",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Marvellous",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Thank you big legend",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Thank you Marcus and your friends , Nice !"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Finally get to see Marcus play the fretless live. Such a sweet feeling & sound. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "what a gentleman",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Marcus singing on the fretless, those lyric moments we don‘t get that often in the pop-slap universe."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "YEAH!  MM always come wit the best live intros! Yessssssssssssssss!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"man, the piano samples on those Nords have gotten quite good, I must say..."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best performance in recent years!",
    "": "",
  },
  {
    ARTIST: "Lumineers",
    LINK: "https://youtu.be/353lHGbvu8o",
    ID: "353lHGbvu8o",
    COMMENT:
      "Don't understand how Woody Harrelson has time to play the drums for these guys in between his acting gigs.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "If The Lumineers dont perform on my funeral im not going.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"""It\'s better to feel pain than nothing at all"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "there are a few things in life that a human being just should not do. disliking the lumineers is one of those things.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Ive never heard a more genuine sounding band.  These guys need to go on tour with the head and the heart.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"this isn\'t music. This is far beyond that. Anyone can make songs but not many can make you ""feel it"". I feel it."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Neyla deserves more attention than she actually receives.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"the drummer always looks like he\'s having the time of his life. Great band altogether, i hope they will be around for many years."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Music is just wow ! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Stubborn Love is literally life.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/Ud6nR6QKNmA",
    ID: "Ud6nR6QKNmA",
    COMMENT: '"Flapper Girl is so underated, such a great song"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"The woman playing the cello, she has the most beautiful smile, the music is pretty good too :P"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "some music is better live and recorded like this than the studio - very tight band",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "\"It's not music, it's magic!\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"And when it came to love, we were not good enough for it"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I wanted to listen to their music without  crying. Impossible.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I am madly in love with The Lumineers! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "My God that woman is gorgeous! To me there is nothing hotter than a girl who plays an instrument!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This Band is so amazing. Can´t wait for the new Album!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She is beautiful omg",
    "": "",
  },
  {
    ARTIST: "Snow Patrol",
    LINK: "https://youtu.be/X80i7-Dq2yg",
    ID: "X80i7-Dq2yg",
    COMMENT:
      "If you want an example of how to mix live sound - this is it - sounds amazing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Incredible. The audio is amazing. The Engineers need a massive credit",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Gary seems to get a genuine kick out of hearing the audience sing his music. The huge smile on his face is adorable.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Gary's light hearted fun attitude along with his relaxed confidence comes thru in a sincere charming way. You can tell he loves what he does.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The performance of “Heal Me” is stunning, epic!!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best band in the world!!??",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing acoustic set. Best I have ever heard.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "WOW....JUST WOW!!! A night I’ll never forget.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wow. They’re such a talented band.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That version of run awesome ♥️♥️♥️♥️",
    "": "",
  },
  {
    ARTIST: "Prince",
    LINK: "https://youtu.be/uAYQUbh8HHA",
    ID: "uAYQUbh8HHA",
    COMMENT:
      "People who never saw Prince in concert have no idea what they missed",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Everyone in this band was a damn good musician.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "always sang  never lip sync and always sound like the record",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He was 24 years old when this was recorded.  Amazing.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Now THAT was a concert! There are no artists like this today.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Do me baby, sexiest song ever written"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The stage was his home, his church."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"He is not a Prince, he is KING."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Jimi Hendrix....Here's the Prince we told you about.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He was only around 23 years old.",
    "": "",
  },
  {
    ARTIST: "Sam Smith",
    LINK: "https://youtu.be/3k-cUy9F1Vc",
    ID: "3k-cUy9F1Vc",
    COMMENT:
      "Finally he is comfortable with himself and I'm living for it............... THAT OUTFIT IS LIFE <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Someone so confident, so in love with their voice, their body, their sexuality and ya\'ll cant seem to handle how amazing this person is."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"he seems so happy, he's litterally glowing, i'm so mesmerized\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love that he’s dancing now. So proud of him",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He is being he's true self and he's glowing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Live Sam. People just need to stop with their negativity, no one cares. Spread positivity!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "They are AMAZING!! AND THEY YES IS THEIR PRONOUN. NON BINARY FINERY.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is absolutely perfection in all sense!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He has a perfect eyeliner and his simply majestic voice",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "LOVE the diversity in his backup dancers! YES representation!",
    "": "",
  },
  {
    ARTIST: "Michael Jackson",
    LINK: "https://youtu.be/Hxgo-Qu-ZZE",
    ID: "Hxgo-Qu-ZZE",
    COMMENT: "The most talented pop music icon that ever existed!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "To Everyone here: You have a great taste in Music!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The best Singer of the world and I believe he isn't death only king of Pop heeeeeeeeeeeeee!!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"No cameras , no smartphones , No Internet ,people were 100% connected to Michael"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "He donate the money off all childreen Houses in Romania ...after the concert what a kind man...beautifull soul",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "B E S T   A R T I S T   O F   A L L   T I M E",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Michael Jackson is the king of pop that nobody will change him being dead",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Not only Michael is gifted, he cared a lot about his fans."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"no one recording , just enjoying Michael Jackson’s talent !!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is the best concert ever ... There will never be another Michael Jackson...",
    "": "",
  },
  {
    ARTIST: "Travis Scott",
    LINK: "https://youtu.be/iaFKqyP_V88",
    ID: "iaFKqyP_V88",
    COMMENT: "travis has the best concerts dont @me",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I almost died. Best time of my life",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "most beautiful thing you’ll ever hear",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The kid who went on stage is lame asf",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Travis is a humble man",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "5% tint dope asf",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "why Travis is goated",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Guy with the phone missed his chance to have a moment",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Astroworld coming",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "“Out Of This World”",
    "": "",
  },
  {
    ARTIST: "Branford Marsalis",
    LINK: "https://youtu.be/sQQ0EvJZvFg",
    ID: "sQQ0EvJZvFg",
    COMMENT: "I can't stop dancing!!! Great quartet and great music!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That bassist was really diggin it",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Jazz is In his Gene!! smooth!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Calderazzo really kicks ass!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Tain and Revis ain't bad either!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I love Brantford. His style is Grown and Sexy and undoubtedly amazing!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Beautiful!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "monster master class!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Performance.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Joey plays hard!",
    "": "",
  },
  {
    ARTIST: "UNDERWORLD",
    LINK: "https://youtu.be/RAUbRjx6ntw",
    ID: "RAUbRjx6ntw",
    COMMENT: "The best Underworld concert I've ever been to.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"nice music, nice video."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Top artists! Thanks!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "as always the best !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wow avesome. Young boys:))",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "u are simply the best!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "\\m/  !!!!!!!!!!!! Excelent !!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "big big like!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Looveeeeeeeeeeeee",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "1st track is very cool! As old favorite Underworld!!!!",
    "": "",
  },
  {
    ARTIST: "Al McKay's Earth Wind & Fire Experience",
    LINK: "https://youtu.be/O3EVsT08Khg",
    ID: "O3EVsT08Khg",
    COMMENT: "You got the best of my love oh oh oh......... Mr. Al Makay",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The real Al Mc Kay",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Genios...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Wow, thank you....that was awesome....Thank you Al for keeping music alive...  :)"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "love it",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Basse Mr. James Manning, hey!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "WOW  Wonderfull band",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Awesome",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Great horns.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "You cannot beat Maurice’s silky tenor voice",
    "": "",
  },
  {
    ARTIST: "BTS",
    LINK: "https://youtu.be/b9cG4DzpL_c",
    ID: "b9cG4DzpL_c",
    COMMENT: "Lets face it Grammys can't afford a BTS stage",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They literally turned an Award Show into a CONCERT.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Sorry Grammys but this was better than your whole show",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This performance proved that BTS didn't forget from where they started",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I can\'t say anything except... ""I feel so proud! I\'m about to cry."""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This shows how the Grammys can't afford a stage for BTS. It's like trying to put a chandelier inside a phone booth xD",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "So Grammys were scared of the quality that BTS serves",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That water dance is one of Jungkook's MOST ICONIC dances ever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Ok. But This whole performance will forever be ICONIC.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I understand why Grammy is scared to invite BTS for a whole performance HAHAHAHA",
    "": "",
  },
  {
    ARTIST: "Disclosure",
    LINK: "https://youtu.be/Hc7igEnZsIs",
    ID: "Hc7igEnZsIs",
    COMMENT: "so soulful",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "What a beautiful voice Sinead Harnett!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Awesome set boys, love you "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Tenderly always gets me moving",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is soooo good. How have i only just seen it!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Freakin love this group!!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Still love this so much!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "IN LOVE WITH THIS",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "omg",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wauw this is awesome!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/0dCi0f8esIk",
    ID: "0dCi0f8esIk",
    COMMENT: "They deserve more than just a 30 minute set",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I LOVE how they play live instruments, and perform vocals. Awesome. "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"I'm getting kinda obsessed with their music, they're so so so good!\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the audience seems to be high",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Music for people who weren't alive for the 90s",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "these guys seem to be so young.....how can they know so much about music??!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "no sleeping during disclosure!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"These guys are the baddest on the planet, no one can touch their music."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"love how people lose their shit when they hear ""when the fire stars to burn"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Bless these boys.",
    "": "",
  },
  {
    ARTIST: "Explosions In The Sky",
    LINK: "https://youtu.be/DNMhiMtNq2g",
    ID: "DNMhiMtNq2g",
    COMMENT:
      "Your hand in mine-the most beautiful creation ever made in post rock.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "After watching this I realize that the earth is not a cold dead place.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Instrumental songs that express more than any lyrics",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"With tired eyes, tired minds, tired souls, we slept"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The ending is one of my favorite things they do for their shows. From absolute chaos to silence. It's perfect.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"GUYS, THAT ENDING."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Although wonderful, especially on headphones, you really have to see them live."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the best bands I've ever seen.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Oh, my favorite. Simply the best"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "...................sounds like the holy water of music to me.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/zDtW-WdYj-E",
    ID: "zDtW-WdYj-E",
    COMMENT: '"lol, that crowd didn\'t even know the lyrics... oh wait"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "are they playing in front of wolves?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Your Hand In Mine has got to be one of the most beautiful arrangements ever written",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"my eyes tear up. Sufism is all about soul, this has soul"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Raaah the sound is too much compressed, we can\'t hear the width of the reveeeerbs :P"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "its always great to see bands that just really love to play live lol",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They always nail Disintegration Anxiety",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Catastrophe and the cure .... such a masterpiece !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The Birth and Death of the Day is an absolute killer.  The intro is the burning sun coming up over the horizon.  So good!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best concert I've ever been to",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/pl8w74mH1Nw",
    ID: "pl8w74mH1Nw",
    COMMENT: '"Dude, this ""The Moon Is Down"" performance is simply SUPERB!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Such a respectful audience. Would love to see them love",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"What a passion, what a performance! A-mazing with a capital A."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "awesome band!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wow amazing setlist",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Nice audience, no wolf howling during the songs and in the breaks. Thumbs up! "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "EITS ROCK! Superb guys thanks!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "explosions in the sky a toda hora !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Your Hand In Mine ♡",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of my favorite!",
    "": "",
  },
  {
    ARTIST: "Mogwai",
    LINK: "https://youtu.be/T2aFPe7mrhg",
    ID: "T2aFPe7mrhg",
    COMMENT:
      '"Funny all the people recording the show on their phones. Could have just enjoyed it, and watched a high quality recording on youtube."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "One of the greatest live bands I've ever seem. So many layers. Great quality here too.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I have loved this band for 20 years.  I can't get enough of them.  ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Nailed it this band is legendary.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I feel like people went deaf after this show.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Best version of ""I\'m Jim morrison i\'m dead"" ever "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "NOOOT LOOOUUD ENOOOUUGH",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"weird. never get tired of listening for 10 years,"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Mogwai Fear Satan",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Genial :)",
    "": "",
  },
  {
    ARTIST: "Tommy Emmanuel",
    LINK: "https://youtu.be/ulTpIP46wFA",
    ID: "ulTpIP46wFA",
    COMMENT: "One of His best concerts and I've seen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Totally random but Tommy\'s hair is actually amazing, especially for 63."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Tommy is like a good wine, hée goes better and better with time, its Incredible"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Phil's song is magical...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Tommy has been playing almost 6 decades....he started at 4 years old in 1959.....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Living legend , guitar god"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "As good as it's ever going to get",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"So much talent in one person! Love, love, LOVE him!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Is there anything he cant play on the guitar?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Great show!!!",
    "": "",
  },
  {
    ARTIST: "Joshua Redman Quartet",
    LINK: "https://youtu.be/E-Nc_m58TYc",
    ID: "E-Nc_m58TYc",
    COMMENT:
      "my God... McBride swings so damn hard it doesn't matter who is soloing over that bass they will be forced to swing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Art Blakey trying to eat Christian Mcb's necklace",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Hahaha, nothing like seeing Blade and Mehldau in suits that are way too big"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Been listening to music for 60 years, this is the best concert I\'ve ever heard in any genre. Astonishing."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "jazz can still swing!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"brilliant, swinging music.  great young guys of  the future."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wow!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Second tune would later be titled Rejoice!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "mr Brad Mehldau on piano",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Whooaw !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/SVNKQtPvv00",
    ID: "SVNKQtPvv00",
    COMMENT: "We need a Tiny Desk Concert with these guys!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Brian Blade is so subtle and sensible with his playing.. it's like hearing the love child of DeJohnette and Elvin Jones",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is great! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is great. Redman is on another planet. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This was absolutely wonderful. Incredible musicians, thank you for the performance."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I truly believe that this quartet is right up there with the John Coltrane Quartet.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing set",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is so perfect! Awesome concert! Awesome musicians! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "HEAVEN MUST BE LIKE THIS!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "INCREDIBLE SYNERGY!!!!!!!!!",
    "": "",
  },
  {
    ARTIST: "FKJ",
    LINK: "https://youtu.be/ftLxvw_eFN0",
    ID: "ftLxvw_eFN0",
    COMMENT: "why is nobody naked",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is what live DJ performances should be like!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This guy is really amazing!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Not only does he make incredible music, but his performances are great too."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "FKJ is insanely talented!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"To be honest, this is the best mixtape i\'ve ever heard"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Never get tired of it!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "FKJ is always on point man he never disappoints.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"FKJ improvising again like a boss, truly a talented guy."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "dude's a genius.",
    "": "",
  },
  {
    ARTIST: "Aphex Twin",
    LINK: "https://youtu.be/5yQRp4j2RQM",
    ID: "5yQRp4j2RQM",
    COMMENT: "Is good to know Richard is visiting the earth nowadays",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Half-Life 3 confirmed.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "STONE IN FOCUS",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Everybody is on drugs at this concert.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "so many drugs were taken",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Rich and his wife bring a 909, seq and some synths and modular up along with the set! SO DOPE!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "that noise you hear while the Stalker is taking you to the Zone",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Last time I was this early, the stretch white limo hadn\'t even hit the car yet."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He deserves Nobel prize for innovation in music and effects",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is the proper rave sound. The actual future to all those sounds we grew up on. Great set.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/961uG4Ixg_Y",
    ID: "961uG4Ixg_Y",
    COMMENT: "richard that was very good",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "bruh lets all just appreciate how well this video is put together",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Nice to see the kids getting down to some dad music",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "7\\",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "girl with the Aphex mask is extremely fashion forward",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "INSANE",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"this man is one of the best creatives, artists, people in the world and nobody will convince me otherwise."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Best, most influential electronic artist of all time. Thank you so much."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "that melody will blow my mind forever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"You\'ve got so many machines, Richard."',
    "": "",
  },
  {
    ARTIST: "Chvrches",
    LINK: "https://youtu.be/1L9iUhiOXbE",
    ID: "1L9iUhiOXbE",
    COMMENT: "Finally!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is the first time I've heard chvrches and I'm impressed.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That was one of the sickest intros I've ever seen....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Shes gotten better at performing, she used to be real shy and quiet while singing."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Why is Tether so underrated",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They should play Strong Hand in their playlist.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Such a great setup!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best KISS show I've ever watched!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "love the face paint!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'm in love with this performance",
    "": "",
  },
  {
    ARTIST: "Belle and Sebastian",
    LINK: "https://youtu.be/r2Y-H0v2pms",
    ID: "r2Y-H0v2pms",
    COMMENT: "I love Belle and Sebastian ❤",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "stu looks like is having the time of his life",
    "": "",
  },
  {
    ARTIST: "Zedd",
    LINK: "https://youtu.be/oVwEiNdpKeE",
    ID: "oVwEiNdpKeE",
    COMMENT: "Zedd is brilliant. So happy this guy exists.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "best zedd track of all time",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is one of the sickest intros out there",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i love this setlist!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "when the molly hits soooo good",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "god level intro !!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "His best set ever... Amazing and full of masterpieces",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That intro gives me goosebumps :D",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "EPIC!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Zedd my mannn",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/t5-PcziC7B0",
    ID: "t5-PcziC7B0",
    COMMENT: "ZEDD did completely amazing!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I feel this man",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He's the only person who got the crowd dancing ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The first song always reminds me of Avicii",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He is the most energetic DJ I've ever seen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love how happy he is. Seeing him happy makes me happy",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I find it extremely cute that he sings along",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This crowd dont deserve him",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "it's so rare that zedd gets to perform but I love it anyway",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Worst crowd ever they don't deserve zedd",
    "": "",
  },
  {
    ARTIST: "Khalid",
    LINK: "https://youtu.be/KdGQu7JRcXw",
    ID: "KdGQu7JRcXw",
    COMMENT: "The only singer who does cardio while singing.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I rarely like every song from an album.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The opening sounds like the opening to a church service haha it’s awesome",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "His band is incredible and they really give that energy he needs to be comfortable in transpositions and octave changes.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i thought he was better live",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'm in love with Khalid's voice <3 <3 <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"He just.... He\'s so good, man."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"This kid is a great talent,I hope he goes far"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love his Vince costume",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "dead crowd",
    "": "",
  },
  {
    ARTIST: "James Brown",
    LINK: "https://youtu.be/m-Oq54jFAAs",
    ID: "m-Oq54jFAAs",
    COMMENT:
      '"When it comes to singing, dancing and entertaining he is the real King."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "James Brown is a national treasure.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"James Brown is like a wild man on stage - all that energy, singing, and dancing! Excellent performance!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"the great James Brown, The King Of Soul."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the best forever James brown",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "See how the band tightened up as James hit the stage!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Does somebody knows who are the two bassists playing ?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "JAMES BROWN--GREATEST PERFORMER THAT EVER LIVED!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is one of the rare times we get to see the great Jimmy Nolan on guitar.  Funk guitar icon !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/QcwhS3VgHpI",
    ID: "QcwhS3VgHpI",
    COMMENT:
      "All you idiots criticizing his performance. At 66 he was STILL better than anyone performing today.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Two Bass players?  If that's what it takes to back up the GFOS. So be it.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "If James Brown was never born there'd be no such word as funky",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The majority of the drunk idiots of the audience didn't deserve such a show.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Dude had a body guard walk on stage with him!  PIMP!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"What an incredible amount of work it must have taken to arrange, choreograph, stage, and rehearse a show like that."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "wow no cellphones in the air",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "THE KING OF FUNK MR. JAMES BROWN",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "James Brown he is a legend",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"now this is my kind of music, live band! you can\'t get no better than this!"',
    "": "",
  },
  {
    ARTIST: "Sarah McLachlan",
    LINK: "https://youtu.be/Yr0vJIs4-pk",
    ID: "Yr0vJIs4-pk",
    COMMENT: "She's so talented :)",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Uniquely Amazing!    She was born to sing.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Thank you Sarah for sharing your gift and spirit.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "one of my favorite singer with a gifted voice!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "What a treasure.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I will listen to her do Possession any way she wants to do it.  What a talent.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "amazing!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/-Afr_MOSAQg",
    ID: "-Afr_MOSAQg",
    COMMENT: "Love you Sarah!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "So sweet that she played I Love You for one of her fans.  Sarah is such a beautiful soul!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "What Talent!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Her voice never changes. .voice of angel and in the arms of an angel .",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Her voice touches & moves my spirit, I always get lost in it"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "An amazing voice I will never get tired of hearing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"So beauiful, so relatable, emotionally... so raw. Touches my soul"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "LOVE THIS ARTIST!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Once in a lifetime artist folks!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She's utterly brilliant. I love her so much",
    "": "",
  },
  {
    ARTIST: "James Blake",
    LINK: "https://youtu.be/o2BVk5tWciI",
    ID: "o2BVk5tWciI",
    COMMENT: "the devil asks James to marry him",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Much respect to James Blake.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Shoutout to the person who screamed,""MARRY ME!"" "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The first 7 minutes are incredible..................................................",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"""To the Last"" was performed absolutely flawlessly!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The lights were spot on, hardly ever see that"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I really want to sing like him",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Love the first 7 minutes, good way to start a show."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "jesus christ this is amazing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best haircut's Ever!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/j4qfT2dxU6E",
    ID: "j4qfT2dxU6E",
    COMMENT:
      "It's difficult for me to comprehend how much of an underrated musician James Blake is. He's an incredible talent.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"hahah the crowd wows got looped with his vocals on ""I never learnt to share"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Might be the best concert I've ever seen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "i like these beats. its like the prefect mix of hip-hop bass lines and techno.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"I think, James Blake is one of the best musicians of our time"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Every time I listen to James Blake I get emotional, his music evokes such an uncontrollable response from me."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"""Aww. Aww. Aww. Omlette, Omlette havin\' it here.""  - that\'s the starting lyrics for you."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "all i have to say is this is profoundly good ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      " what a brilliant performance and brilliant song! love it so much",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The opening song tho. ",
    "": "",
  },
  {
    ARTIST: "Bon Iver",
    LINK: "https://youtu.be/YJNi7aRwUzU",
    ID: "YJNi7aRwUzU",
    COMMENT:
      "So much credit to whoever mixed the audio. They did an incredible job",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The drummer looks like Socrates",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I feel like attending a Bon Iver concert would be a spiritual experience",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This DEFINITELY needs to be set as a live album and put on itunes, spotify etc. Incredible performance!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Imagine Bon Iver and Sigur rós in an album together",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The dislike button should be disabled for this masterpiece.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The dude on drums plays with so much raw emotion",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This might be the most beautiful version of Creature Fear I've ever heard",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is a masterpiece.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "His songs sound like someone accidentally fell on a piano but hit the perfect note.",
    "": "",
  },
  {
    ARTIST: "Kraftwerk",
    LINK: "https://youtu.be/vNoFHdlMrtI",
    ID: "vNoFHdlMrtI",
    COMMENT:
      '"""I guess you guys aren\'t ready for that yet, but your kids are gonna love it!"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "MUSIC NON STOP !!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The faces on people wondering wtf is happening. Brilliant.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best Boiler Room ever!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "is this the future or the past????",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Stone age of electronic music.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the moment techno was born",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "rave whistle was invented at this show",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The camera crew got a bit experimental also.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Techno rave is made by Germany. First Base line ever.",
    "": "",
  },
  {
    ARTIST: "Kylie Minogue",
    LINK: "https://youtu.be/xqtS6Meh5R4",
    ID: "xqtS6Meh5R4",
    COMMENT:
      "Madonna admires Kylie and Kylie admires madonna. Enough said. You both rock. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is the reason why she is so sucessful",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'D SAY SHE IS THE QUEEN OF LIVE SHOWS :)",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Kylie is the Queen... <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing gig she's so down to earth.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Kylie the Diva! She can rock costumes like this and still look fabulous haha!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Queen of pop with out a doubt",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the Best show girl !! ❤❤",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Kylie is a wonderful woman. She\'ll the queen of international super-POP, forever."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Kylie rocks,amazing live performance!"',
    "": "",
  },
  {
    ARTIST: "Snoop Dogg",
    LINK: "https://youtu.be/6_h75JXBnSo",
    ID: "6_h75JXBnSo",
    COMMENT:
      "how bout the band?! DAAAAAMN! Hope they're still the same members! The drummer and bass player were killin it!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Nawww that dead crowd don't deserve Snoop",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Snoop dogg them damn musicians right man idk wat they was puffin on but damn boi",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Drummer is so sickkkkkkk -",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Soopafly on the keyboard!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "No setlist because everyone watching this is high lol",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "called it. Excellent performance.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Snoop Killed It.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i luv this guy no homo.... great show Uncle Snoop",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "REST IN PEACE LOS (Drummer)",
    "": "",
  },
  {
    ARTIST: "Harry Styles",
    LINK: "https://youtu.be/kxLG2yqTPWU",
    ID: "kxLG2yqTPWU",
    COMMENT:
      '"""hi, i\'m harry styles, i\'m sixteen, i work in a bakery"" iconic :)"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "It’s just the cutest thing that Harry just introduces himself like no one knows who he is",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "WHY IS THIS CROWD SO DRY I WOULD HAVE BEEN GOING OFF MY HEAD",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I think we all know that Harry is going to be remembered as another iconic English singer and I’m so happy to witness it lol",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The most amazing thing about Harry is that he needs no auto tune. His voice is so naturally beautiful and smooth. It’s crazy amazing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Harry styles is someone no one can say anything negative about.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I’m telling my kids this was Jesus Christ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "the dangerous thing about harry styles is that his looks are just a bonus",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I honestly cann't trust people who don' t like Harry styles",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "this guy is just RIDICULOUSLY hot",
    "": "",
  },
  {
    ARTIST: "Taylor Swift",
    LINK: "https://youtu.be/_t-fhPUPMrY",
    ID: "_t-fhPUPMrY",
    COMMENT:
      "The only reason why I wanna be rich is to afford to have Taylor Swift sing Lover live at my wedding reception. Periodttttt",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I wonder if Taylor’s parents realized they were making history when they bought her her first guitar",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i love that she always introduces herself like no one knows her",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I will never grow tired of Taylor introducing herself like, ""hi, I am Taylor""."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She literally could turn any event into her concert",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"CRUEL SUMMER, MISS AMERICANA & CORNELIA STREET DESERVES MOOOOORE"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"She really does know how to interact with the audience & give meaningful, articulate speeches that people wouldn\'t get bored of.  Truly an icon."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'm so obsessed with her. Personality and music. She's the bomb.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This girl is like wine: every year is better I mean prettier and as performer amazing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "She is the only artist who gave credit to the other co-artists while performing on stage.. I LOVE HER!!!!!!❤",
    "": "",
  },
  {
    ARTIST: "Post Malone",
    LINK: "https://youtu.be/eCto5AUNfyo",
    ID: "eCto5AUNfyo",
    COMMENT: '"Circles is not just a song, it\'s an emotion."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Posty really can’t make a bad song. Circles is so good!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Circles is going to be a big hit when it officially comes out",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Goodbyes is such a good song, never hear anyone talk about how good it is"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Ummmmm is that Sublime as his Band???? WTF????? LEGENDARY POST!!!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Feeling Whitney is so underrated. Especially this performance of the song is awesome",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Why is circles my favorite song and it isn’t even out yet",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Circles got that Fleetwood Mac vibe",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "“White Iverson is probably my only good song” ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"the dude on the back screaming ""give him a cigarette"" is a legend"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/LRxYHsEJKgI",
    ID: "LRxYHsEJKgI",
    COMMENT:
      "hes like ready to bed then the organizer call him to perform on stage.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Posty deserves better crowds than this man",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "HE IS TOO NICE FOR THIS WORLD",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Post Malone is one of the most humble and nicest rappers out there! Truly cares about his fans...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Only posty can perform with his Crocs in front of a huge crowd",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This makes me miss his curls so much ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "posty so nice stopping the show to help someone",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Post malone wearing crocs in a concert",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I'm a fan of old school music but wen I come across this dude hes cool as",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "“I love you” hahaha",
    "": "",
  },
  {
    ARTIST: "Whitney Houston",
    LINK: "https://youtu.be/N5su1XtMMsM",
    ID: "N5su1XtMMsM",
    COMMENT: "She was so amazing!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She was soo  beautiful!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Great!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "wowwww",
    "": "",
  },
  {
    ARTIST: "Bob Marley",
    LINK: "https://youtu.be/bLkfzVSp49c",
    ID: "bLkfzVSp49c",
    COMMENT:
      "He sings and tells a story of how we should all be. He knew about troubled times and he sang songs of One Love.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "My youngest son's name is 'Marley'.  Bob is a big deal in our house.  Awesome day!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"What a powerful show! Amazings Bob Marley & The Wailers. Carlton Barret\'s drum work in this concert is exquisite, what great musicians !!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I’m a massive Marley fan this is cool",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This man gave us the peace the world needed",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Bob marley will help us through this messy world at the moment",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Rise all freedom fighters",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The best of all times .",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "We want to be free that's all",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Oh my gooooooood he is so extraordinary",
    "": "",
  },
  {
    ARTIST: "Alicia Keys",
    LINK: "https://youtu.be/uJW69FjTu7o",
    ID: "uJW69FjTu7o",
    COMMENT: "Love Alicia!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Alicia is so different than any other artists and i like that unique style",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"ALicia is incredible, emotional. Her music makes me feel shivers"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She loves to get outside the box.  Versatility.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Alicia is the kind of artist where her music really speaks to you. For that, I love her so much!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"An amazing person who has never lost touch with reality, whilst attaining momentous fame, and the most amazing singer ever.  "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Love you Alicia!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Her voice is so unique",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Alicia Keys can play the piano and sing at the same time",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This lady is awesome in every way",
    "": "",
  },
  {
    ARTIST: "Damien Rice",
    LINK: "https://youtu.be/cL7QZv9wCZ8",
    ID: "cL7QZv9wCZ8",
    COMMENT:
      "Cheers Darlin' is quite possibly the best musical autobiographical performance Ive ever seen.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Rice is just genius personified. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Incredible talent",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Amazing, what a showman!! he only needs a guitar, a piano and a glass of wine, no need of backup singers nor band."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"What a songwriter and performer... even ""authentically drunk"" :p. Thats taking your art seriously!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I wonder what that Cheers Darlin girl would think if she heard it now.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Damien Rice is not a Music Artist Damien is the Music KING !!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "when i feel dead i play this and i feel a little alive",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I hope he gets royalties from Ed sheran",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "one man on a stage with just a guitar. he is such a talent man",
    "": "",
  },
  {
    ARTIST: "2CELLOS",
    LINK: "https://youtu.be/qew2m1UdbXk",
    ID: "qew2m1UdbXk",
    COMMENT:
      "I just love to see all the happy people! Look at their faces: that’s how we all ought to look more often. Happiness to everyone!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "thanks for your music.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Can we all just get an upvote for that epic drummer???",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"under tremendous stress, accidentially found this. A real remedy. Thank you."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is the first time that music has touched my heart & soul --  like Freddie Mercury & Queen -- almost 50 years ago",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "These two are real crazy and i really crazy love them.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The Jimmy Hendrix of the Cello.  These 2 guys took their instruments to a new level..... Hendrix would approve!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "*NEVER IN HISTORY HAVE 2 CELLOS BEEN TOTALLY MASTERED LIKE THIS*",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "simply magic!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"You bring my tears, timeless joy & more"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/CGU2BBeKaXM",
    ID: "CGU2BBeKaXM",
    COMMENT: "They are wonderful",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "These guys are so incredible......I am stunned listening to them ...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"If these talented musicians don\'t move you, then you are dead inside.  Just. Magnificent. ♥♥♥♥♥♥♥♥♥♥"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "it is almost impossible  to turn them off.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The cello is my favourite instrument. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"im an AC/DC fan , and listening for the first time this group and they way they played the songs that i love ..just brilliant.... YOU GUYS ROCK!!!!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "YOU'RE EXTREMELY AMAAAAAZIIIINGG!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "REALLY AWEEESOMEEE!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I nevere thought that can be possible to play that Rock & roll music with cellos. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "These guys are outstanding..",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/Sk5zxA9UP2Q",
    ID: "Sk5zxA9UP2Q",
    COMMENT:
      "I think 2 CELLOS are the no 1 cello players in the world & I love 2 CELLOS",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "stimulating and beautiful harmonic blend.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They are fantastic!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing ..",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is fantastic!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This. Was. Stunning. Loved every bit",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "A great mixture of passion and classic. Fabulous!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Absolutely stunning musical performance by two marvelous young men.  An old lady said so!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "GENIAL! 2 guys SO GENIUS. THE DIVINE HUMAN(ITY)! LOVE them",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Blessings to you both.",
    "": "",
  },
  {
    ARTIST: "Edith Piaf",
    LINK: "https://youtu.be/O_ha3rustRw",
    ID: "O_ha3rustRw",
    COMMENT:
      "Elle est sans discussion possble la plus grande artiste de music hall en France.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Edith é excelente!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Magnifique !",
    "": "",
  },
  {
    ARTIST: "New Order",
    LINK: "https://youtu.be/0Bu1fkgUM7s",
    ID: "0Bu1fkgUM7s",
    COMMENT: "Stephen Paul David Morris = Human drum machine.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I feel like crying when I hear Love Will Tear Us Apart by New Order, long live Joy Division forever."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "His voice has aged well. Still sounds like he's my age.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "They sound awesome. Still better then the majority of the crap put out today.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "One of the seminal connections between rock and electronic dance music. Still sounds relevant and great.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "When they play Joy Division songs is inpossible to me don't get emotional",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love Joy Division and New Order.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The only band that went through a time machine and brought  future to the past. Their music is way ahead of their time. NEW ORDER FOREVER!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Absolutely brilliant. Keep coming back for more. Really good gig.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I just love the way Bernard laughs at himself after realizing he screwed up the lyrics.",
    "": "",
  },
  {
    ARTIST: "Peggy Gou",
    LINK: "https://youtu.be/-UOMvxh4MYU",
    ID: "-UOMvxh4MYU",
    COMMENT:
      '"cellphones people, why would you film it when its live and also recorded?"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I would be so paranoid about the sculptures in danger...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "What a beautiful place to play.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Mixing or not, I\'m liking this"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Track is pure beats",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "My new favourite set! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"omg i love her already, she is killing it"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "All those Smartphone Apes in the Crowd omfg....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"I really love, that she's playin also the old stuff from the 90'. Makes me feel young again :)\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The most beautiful woman on the planet slaying the game.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/nKHpbiYCtDQ",
    ID: "nKHpbiYCtDQ",
    COMMENT:
      "Out to Peggy Gou / Peggy Shoe / Peggy Boo (depending on drunkness)",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Bruce Willis has quite a good taste in music",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I DIED DEAD.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I think Peggy is cool.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "just here for all the men with subpar mixing skills analyzing her set",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i respect the black clout goggles",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "what a set peggy... ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She’s so cute",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"anyone noticing kids on her back, i think they lost from their parent"',
    "": "",
  },
];

module.exports = blue;
