const red = [
  {
    ARTIST: "Rage Against the Machine",
    LINK: "https://youtu.be/F9S-JVKw0mE",
    ID: "F9S-JVKw0mE",
    COMMENT: "Zach's anger is a gift to humanity. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Rage makes me wanna flip a cop car",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "RAGE AGAINST THE MACHINE IS MODERN DAY THERAPY TO MY EARS.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I tried telling my mom what they were singing at the end but she smashed me with a wooden spoon.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I actually feel sorry for Metallica who had to play after them.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Some of the most important music ever written. These guys give every ounce of energy they can give.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"There's never been a band like RATM, they're one of a kind. One of the greatest of all time.\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "We need a little Rage right now. This is for the people of the Sun.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"de la Rocha is one of the greatest rappers of all time, but because he does it in a rock format, you never his name mentioned."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Governments invented covid19 to stop ratm tours",
    "": "",
  },
  {
    ARTIST: "Korn",
    LINK: "https://youtu.be/jR88BgYMlbQ",
    ID: "jR88BgYMlbQ",
    COMMENT: "Are you READY!?!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Crowd turns into Liquid",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I wonder how many people went with their friends, went crowd surfing and then could never find the people they came with after that"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "and this is how the 90s said goodbye",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "David Sylveria was a sick drummer.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"A crowd with no phones, that's something you'll never see again :(\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "munkys frog leap dance move",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"not gonna lie, I\'ll always miss the 80s and 90s"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Falling Away From Me was really sick.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They're one of the literal best bands ever.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/NpSKLOjC0ts",
    ID: "NpSKLOjC0ts",
    COMMENT:
      '"damn this music reminds me of not doing homework, playing n64, drinking orange soda, coming inside from rollerblading"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "late 90's nu metal era is forever the shit.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Iphone free crowd. Those were the days. Proper mosh pit too!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "THAT MOUSTACHE.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Dave Silveria is so underrated.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "THE days of Adidas vs Puma.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"PA/Sound was amazing!  The guitars, amps and pedals, everything was perfect.  That bit with Ice Cube was amazing."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Can't explain the feeling of listening to korn songs <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Munky getting really into it",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Silveira\'s chops so intense, them sudden blasts.."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/toBpygISzeM",
    ID: "toBpygISzeM",
    COMMENT:
      '"Why do people record when there are professional recordings only a few days after, they ruin the shows"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I think Brixton Academy is one of my favourite concerts the sound is so much better cause it is indoors and small and the drums and guitars sound way better there than most concerts.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The energy it must take for JD to belt out these vocals for an entire show....fukn impressive!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"This is sad, Get rid of them phones and have a good time!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I still love KoRn!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love that I can name every song from every concert haha",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "My favourite band till the day I die.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "dead bodies everywhere!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "my dream watching KORN concert :-(",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Dave Mustaine xD",
    "": "",
  },
  {
    ARTIST: "Queen",
    LINK: "https://youtu.be/SbWLWNXsVxA",
    ID: "SbWLWNXsVxA",
    COMMENT:
      '"This cleared my acne, cured my depression, and gave me good grades"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "All songs of Queen are great",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "He truly was in a league of his own.  His live performances where just out of this world.  Nobody will ever come close to this mans ability",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"There’s a love affair going on between Freddie and his audience, both ways."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I’ve been told I’m obsessed with Queen and Freddie. Uh yeah !!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"I couldn’t stop looking at Deaky, he’s just so mesmerising"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Freddie Mercury is a total performer ever in the history of music",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Nobody talks about Freddie's good shape. Did he workout? what a great body!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Oh my god. They were and are amazing. Freddie was beyond incredible.  I’m in awe.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "THE BEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEST",
    "": "",
  },
  {
    ARTIST: "Hives",
    LINK: "https://youtu.be/e2f0Ff2cfQY",
    ID: "e2f0Ff2cfQY",
    COMMENT: "such a underrated band",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Damn, that drummer gets one hell of a cardio workout..."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This is a perfect example of how every musician should act, BE ACE AND HAVE A BLOODY GOOD TIME"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Damn, these guys are amazing live. "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Gentlemen doing punk",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"music\'s missing danger, but these guys are doing a good job roughing it up"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That bass is fuzzrocious",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Something is wrong with his microphone... at first I thought it is still turned off, but maybe it is too quiet because the others sound much louder... weird o.O"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That was a great performance!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "clockwork orange",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/4d_xk7sSIbU",
    ID: "4d_xk7sSIbU",
    COMMENT:
      '"Maybe one of the most underrated frontmen and live acts since the 80s, swear down"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"The Hives are when The Stooges, Pixies, The B 52\'s, The Clash and DEVO all have an overly mischievous musical baby they will have to eventually put on Ritalin. Too much fun!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Good lord, what a HOT CROWD!  So many concerts nowadays, people just stand silent.  These gents are what live music is all about"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love the insane style of Nicholaus Arson.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Sometimes i\'m really proud of being a swede. Best live band ever, Fagersta finest."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Good performance",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Hives in their prime!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "still the best live band in the world!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "THIS IS ROCK AND ROLL THIS IS THE HIVES",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "ohh boy",
    "": "",
  },
  {
    ARTIST: "Papa Roach",
    LINK: "https://youtu.be/4w_OVYeea6c",
    ID: "4w_OVYeea6c",
    COMMENT:
      "Respect  to Papa Roach. So many years playing and they still show so much energy!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This man to this day still sings his heart out, so proud to be a fan."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The crowd is too calm at the beggining. And Jakob awake them ... nice job",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'm really pleased with this one. Hair was on point",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Shaddix is a monster",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is one of the best Papa Roach's perfomances I've seen in  while! Also Anthony is doing an amazing job.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"how the hell does he sounds so good for so long, this guy is a rare gem"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Jacoby is the best front man of a generation, always on point."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Take my moneeeeey!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They still rock!!! Great sound!  awesome!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/CFecEDvIxok",
    ID: "CFecEDvIxok",
    COMMENT: "Mixing guy is a bassist.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Papa Bass - i like",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Its like im hearing the guitar from a phone speaker and the bass super boosted",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Good band  ; )  let's rock",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Last Resort",
    "": "",
  },
  {
    ARTIST: "Linkin Park",
    LINK: "https://youtu.be/7Mxg4VkkRRI",
    ID: "7Mxg4VkkRRI",
    COMMENT: "I WENT WITH MY MOM! THANKS MOM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Yup, Linkin Park still hits harder than Covid."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is the best concert of their entire career.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Whenever Chester screams, the crowd just go Crazy . What a power ."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "So goddamn perfect it sounds like a studio recording",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This was his prime. The power and the raspy voice at the same time.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "How does chester sing like that for a whole concert? crazy",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Chester one of those people who sound better live",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Cant believe how good Chesters voice is live. Crazy.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the few bands that I will always think sound better live",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/VEljwjZen-A",
    ID: "VEljwjZen-A",
    COMMENT:
      "There's no doubt this was one of Chesters best vocal performances. The stars aligned for him that night. True art here.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Greatest band of all time.Wish i could have seen them in concert with chester live.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "My favourite band ever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This concert is chester's legacy",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "So beautiful sound",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is one of the best performances i've ever seen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Unbelievable. I have a background in classical voice and I'm a professional pianist.  His voice endurance is arguably the greatest of all time.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Watching these LP live shows makes me cry",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Chesters voice was on point in this concert",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "MY GOD THIS IS GOOD---WISH I WAS THERE!",
    "": "",
  },
  {
    ARTIST: "AC/DC",
    LINK: "https://youtu.be/lfSWQtCpEFk",
    ID: "lfSWQtCpEFk",
    COMMENT:
      "“We don’t speak spanish very well but we speak rock n’ roll very good”",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "it’s one of my favourite live concerts ever! Brilliant stuff!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This crowd is FUKIN Insane!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "THE BIGGEST CONCERT IN HISTORY TO TAKE PLACE AT A SECOND DIVISION CLUB STADIUM",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The greatest Rock and Roll band EVER And what a concert",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"""And God Said: Let There Be Rock!"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "River Plate is the ultimate audience for any rock band.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"And this, kids, is what real music means. Listen and learn."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Ac dc live at circus krone full.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is exectley what Human beeing is about. Love it",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/epSe9V5ngeo",
    ID: "epSe9V5ngeo",
    COMMENT:
      "bon scott ... best hard rock vocalist of all time... in my opinion",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Bon Scotts jeans had to be surgically removed after the show.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "True legends of rock",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"my mom was always blasting acdc when I was little, thanks mom!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Angus Young jumping all around on stage with his guitar yet keeping perfect control...always impresses",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of my first concerts.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Angus has some of the best vibrato I've ever heard.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Goddam Bon Scott was the real deal!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Bon Scott probably made groupies pregnant just by looking at them.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Damn Bon could sing like a beast live.",
    "": "",
  },
  {
    ARTIST: "Slipknot",
    LINK: "https://youtu.be/QO3j9niG1Og",
    ID: "QO3j9niG1Og",
    COMMENT:
      "Why does Corey’s mask make him look like a scary Ed Sheeran in this?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the only harmless thing in this concert is the giraffe",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Corey’s voice is a lot better now than on the gray chapter era",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "AAAAAAAARRRRGGGGGGHHHHHH",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Corey’s mask is what I look like when my allergies struck",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Coreys mask looks like it has melted into his face",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Slipknot are like wine The more it ages, the more is good"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"You can tell how proud Corey is of his screams, he’s practically grinning the whole concert."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Corey don\'t need autotune, autotune needs him."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The VOCALS are out of this WORLD!",
    "": "",
  },
  {
    ARTIST: "Metallica",
    LINK: "https://youtu.be/zFJ4H0t7dWs",
    ID: "zFJ4H0t7dWs",
    COMMENT:
      '"""Bleeding Me"" is such a beautiful song. And quite underrated too."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Who’s hoping for Kirk or James to do the intro this time?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "they need to play bleeding me again. absolutely one of their BEST songs",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Hetfield looking great here. Goatee James is underrated.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Metallica has insane luck with bassists",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "We need more bleeding me in Setlists",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Metallica is my therapy.  So  happy they exist, the earth would be a lesser place without them."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Creeping Death will forever be the best opener",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The best band of the world. My friends forever ...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Devils Dance was definitely the surprise of this show",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/mJje9Xpp5GE",
    ID: "mJje9Xpp5GE",
    COMMENT:
      "One of Metallica’s greatest accomplishments is  how they’ve managed to appeal to the same age group decade after decade while also retaining their aging fanbases. What a timeless band!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This was an absolutely kick ass show.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "First gig I went to after kicking cancer's ass where I had energy for the whole set.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "It’s so cool seeing the raindrops fly everywhere when Lars plays his drums!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "That little solo in St. Anger was more unexpected than the Spanish inquisition",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The more pressure there is on Metallica, the better they play."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I still can’t get over how badass master of puppets was",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"THAT EXTENDED VERSION OF ""MEMORY"" IS SUPER COOL !!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Props to Trujjillo for not dying his grey.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "When playing 'One' and trenchfoot is an actual possibility",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/pjGYBktU71I",
    ID: "pjGYBktU71I",
    COMMENT:
      '"The era when James went full trailer trash, Kirk looked like Michael Jackson, and Jason was just a head banging neck."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"I call this haircut on James, “The Kentucky Gentleman”"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"couple of good rare ones on the setlist, can\'t believe they played Enter Sandman"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Is it just me or does Newsted make everything better.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Jason Newsted was just perfect match for the band",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "50% of the metal energy in concert is due to Jason.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "It would be nice if James and Kirk would crawl out of the hole they're hiding in and introduce one of these shows!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The God that failed , proshot in 1994 , finally"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This was peak James hairstyle. So badass",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Jason Newsted Forever",
    "": "",
  },
  {
    ARTIST: "Nine Inch Nails",
    LINK: "https://youtu.be/LBC3NXnN8y4",
    ID: "LBC3NXnN8y4",
    COMMENT:
      "Trent Reznor is the proof you don't need tattoos or piercings to be cool.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Thank you Trent.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That drummer is absolutely killing it.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Trents looks 40.  Mick Jagger looks 1,000."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"The bass is so good especially with a nice set or headphones, they were on their shit this night"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "absolutely love how the world keeps changing but his stage still looks like a map from Quake.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That bass player just went to play bass. He never moved.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "How about that drummer?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Who the Hell is this amazing drummer? Crazy energy",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Back up singer is Lisa Fischer... ",
    "": "",
  },
  {
    ARTIST: "Green Day",
    LINK: "https://youtu.be/dO-Y_fMuc4c",
    ID: "dO-Y_fMuc4c",
    COMMENT:
      "Billie is the only middle aged man in the world that could still pass as a teenager",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Green Day are always so damn amazing live! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Billie Unlocks Double Jumping",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I admire everyone today who still loves new and old green day",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Billie is the only middle aged man that vendors asks for ID when buying alcohol...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Who ever mixed this you are a god",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Billie forgot his eyeliner",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Looks epic!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Revolution Road :/",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Come on billie, where\'s When i come around?!"',
    "": "",
  },
  {
    ARTIST: "Liam Gallagher",
    LINK: "https://youtu.be/37BDUBe6Tfg",
    ID: "37BDUBe6Tfg",
    COMMENT: "All the Oasis tunes sound better when Bonehead is on the guitar.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Bonehead: The only guy in his 50s who can pull off wearing an adidas tracksuit.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Ive just realised bonehead was what I liked about Oasis's sound",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Liam seems to feel more confident with Bonehead on stage. He should play permanently. We have 2/3 of Oasis there.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Has there ever been a cooler man to play the tambourine",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Nobody is gonna say something about Sad Song? Greatest live version ever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Looks like Bonehead has given Liam's band a lesson or two...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Liam doesn't need Noel But Liam needs Bonehead !!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Can’t have enough Bonehead’s comments. He’s fkin LEGEND",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Noel needs Liam so much more than Liam needs Noel.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/EnzVduS-vyE",
    ID: "EnzVduS-vyE",
    COMMENT: "biblical",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best liams been in 20 years! The man is back.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Rock N Roll is Liam Gallagher.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Liam is on absolute fire! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Epic and BIBLICAL!! It's historic!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Amazing , John Lennon reincarnated"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Bang on, ""gone"" was amazing"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Gone is a huge tune!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One word only: EPIC!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Once is one hell of a song",
    "": "",
  },
  {
    ARTIST: "Noel Gallagher's High Flying Birds",
    LINK: "https://youtu.be/WyYWRrqLOSA",
    ID: "WyYWRrqLOSA",
    COMMENT:
      '"Noel just seems to get better and better as a singer, songwriter and guitarist. Such a legend."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Man who built the moon is a tune",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Liam is an entertainer, Noel is an artist"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "´Alone on the rope´ should be on an album. Genius",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Awesome I cant believe he played alone on the rope",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love how Gem plays the guitar!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Alone On The Rope is such an incredible song.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This man is GOD.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Fort Knox is the perfect opening tune for a live performance!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Really respect Noel as an artist, love him!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/BbEEcP79IDI",
    ID: "BbEEcP79IDI",
    COMMENT: "NGHFB are amazing! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Pretty cool that he uses the Adidas J-200 for the Oasis numbers",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Yeah baby yeah!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/GnnfXPJxnCo",
    ID: "GnnfXPJxnCo",
    COMMENT: "Only Noel can open a show with a B side. Brilliant....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"If Oasis gets back together, they\'re going to make one of the best albums ever. Both Noel and Liam are on fire."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Never understood why people use their phones to record a gig which is being recorded with TV cameras. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This audio is stunning. Well done. Also, this performance is the reason why Oasis won\'t reform. Noel is on fire at the moment."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"Noel hasn't lost it. The voice isn't any different from the recorded tunes, if not better.\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is arguably one of Noel's best sets. And it also pretty much says oasis are done. He doesn't need them. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This sounds absolutely incredible. Unreal Audio, Noel never disappoints like."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"And Liam said Noel was the ""weird"" one.  Maybe Liam is an alien."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Everybody\'s On The Run, The Dying Of The Light and If I Had A Gun gave me goose bumps..."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I can't think of anyone else who still writes songs like this.",
    "": "",
  },
  {
    ARTIST: "Foo Fighters",
    LINK: "https://youtu.be/jcwBsntqjmY",
    ID: "jcwBsntqjmY",
    COMMENT:
      "The fact they got Jimmy Page and John Paul Jones is the coolest thing ever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the best shows all time.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"A concert without smartphones, that must be crazy."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"""Dude, where are you going?"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "When Dave sings he looks like he’s riding a horse",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The best show I've ever seen.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Dave is my new god, after Frusciante, but who knows... OMG love this guy sooo much. Btw drummer is amazing too. Nope, Dave IS the best!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Time to fight the foo",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Times like these makes me wanna cry",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "whenever i saw Pat playing...i see happiness",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/A8z6rbmx7Mg",
    ID: "A8z6rbmx7Mg",
    COMMENT: "Short haired Dave scares me",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"The mix is absolutely insane, might be the heaviest live recording of theirs I\'ve ever heard"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The foos never disappoint.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This show is incredible",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They should play In Your Honor and DOA more often!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Taylor with short hair Looks like a member of the bee gees",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "It's times like these you learn to live again...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the best groups ever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Still My favorite all time band.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the most awesome shows ever",
    "": "",
  },
  {
    ARTIST: "Red Hot Chili Peppers",
    LINK: "https://youtu.be/PNd7cRl6Bfg",
    ID: "PNd7cRl6Bfg",
    COMMENT: "This is the very first show of their Californication tour",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Emit remmus is a great opening",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Slap in you face!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "that frusciante fuzzy tone is amazing!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing quality!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "best performance of power of equality.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Oooooooouhhhh how off was Frusciante in Around the World hahahaha",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Temp rising and the heat intensifies",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "John frusciante feeling",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Got scared when I saw flea up close sigh",
    "": "",
  },
  {
    ARTIST: "Guns N' Roses",
    LINK: "https://youtu.be/UTulnklNm2Q",
    ID: "UTulnklNm2Q",
    COMMENT: "I can’t believe SLASH is 54 years old.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Axl sounds more like mickey.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"If Axl had stuck with his Brownstone voice on Slither , it would have been epic!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Best Band in the worl !!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Oh, the old good times when we could rock outside..."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I’m impressed that Axl did this song.  Slither I mean.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Axl would sound so much better if he just went down an octave.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "When your bassist sounds better than the lead singer.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They should do these every Monday like Metallica.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Axl is awesome but slash carried the show i havent see him so energetic for a long time",
    "": "",
  },
  {
    ARTIST: "Sex Pistols",
    LINK: "https://youtu.be/QBVDSz5Qd6g",
    ID: "QBVDSz5Qd6g",
    COMMENT: "This sounds so bad and so damn good at tha same time. Legends",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Johnny Rotten is an incredible front man, sarcastic, cynical and with a very original voice, he is the joker on the stage"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I can't complain. Sid's bass playing skills are wayyy better than mine lmao",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "drummer deserves more credit than he got...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"i don\'t care what the general consensus is, I love this show."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "johnny looks like he wishes he was in pink floyd.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "John Lydon. One of the legendary Voices.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "It's a miracle they got through this one hour show still standing up.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"For a guy who can’t play bass, „not even a bit“ Sid‘s playing is pretty solid."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Pretty vacant has got to be one of the best songs ever written.",
    "": "",
  },
  {
    ARTIST: "Lou Reed",
    LINK: "https://youtu.be/yOoXjYppyMM",
    ID: "yOoXjYppyMM",
    COMMENT: "Lou Reed had really amazing posture.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"We need more volume to Mr. Robert Quine, please"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Robert Quine on Lead Guitar!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Lou Read is one of the most underrated artists ever.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Makes my day. R&R sure is fun!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He's actually happy",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"""...her life was saved by rock n roll"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I can die peacefully having seen this dude (and band)  live",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Man his voice sounds just fine. Usually at this point you'd notice some weakness.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Incredible.",
    "": "",
  },
  {
    ARTIST: "Grateful Dead",
    LINK: "https://youtu.be/VnCvS2A7REo",
    ID: "VnCvS2A7REo",
    COMMENT: "There is literally NOTHING better than a happy Jerry Garcia.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Stay gold, Brent."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "May the wings of Angels surround and protect you like the softest warmest blanket you have ever felt.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Imagine that! Bobby with Bobbie pins in his hair",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Turn off your mind, relax and float down stream..."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This is an excellent show....best “eyes” ever...& “he’s gone” on point!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This concert changed my life.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "My goodness the boys were hot tonight. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "With a doubt! Nothing like a Jerry smile to make everything perfect!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That was Awesome.... ",
    "": "",
  },
  {
    ARTIST: "Sum 41",
    LINK: "https://youtu.be/DTIKGtUbRqU",
    ID: "DTIKGtUbRqU",
    COMMENT:
      "This just proves that small venues are the best for the band and crowd interaction.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Props to the sound guy. This sounds AMAZING!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "It's great to see Deryck back after all that shit! Thanks man!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Whoever mixed the audio is a God those drums sound amazing!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This is what a concert is about, the band and crowd having a good time"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "These guys were always a very different breed than the average pop-punk Mtv fodder bands of the early millennium.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"These guys are like wine, the older they gets the better they are!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Now this is a great crowd: no phones and enjoying the moment.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The sound quality of this recording is incredible",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That new song sounds even better live!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/6F7qretnMAs",
    ID: "6F7qretnMAs",
    COMMENT: "Epic drumstick fail",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "First three records are classy and flawless.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "oh god that fat lip intro was spot on",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "nostalgia",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I wish the bass was louder",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"That random Slayer cover cracked me up, I believe Brownsound is a huge Thrash fan, I got his solo CD with his brother very good shit!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "someone likes slayer",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is cool",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Aha wrong lyrics during rhythms that's cool",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Ahhhhh back when they were cool",
    "": "",
  },
  {
    ARTIST: "My Chemical Romance",
    LINK: "https://youtu.be/Ud2eziOjjTo",
    ID: "Ud2eziOjjTo",
    COMMENT: "when my chemical romance is more active than twenty one pilots",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "STILL THE BEST BAND EVER !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"""I\'m not a hero"" is one of the most incorrect things Gerard Way has said."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is the closest i will ever be to an mcr concert...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "WHEN GERARD CHICKEN DANCED AROUND THE STAGE WHEN RAY WAS DOING HIS SOLO DURING TEENAGERS",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Forever thinking about how Frank stayed onstage to watch Gerard sing the last song",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I can’t comprehend how some people don’t like mcr. They are perfect.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Anyone else notice gerard's chicken sance during teenagers?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I’m simping so hard for Gerard in this concert",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is gotta be Gerard's best look",
    "": "",
  },
  {
    ARTIST: "Paul McCartney",
    LINK: "https://youtu.be/1QGxFpSb6Sc",
    ID: "1QGxFpSb6Sc",
    COMMENT:
      "He’s nearly 80 and he can still perform Helter Skelter. One statue does not do Paul McCartney justice.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Linda would be proud.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The word LEGEND doesn't do Paul McCartney justice. The greatest of all times!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Who is complaining about his voice !!! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "We  are all blessed to  have Paul McCartney in our life's",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The Greatest Songwriter Who Ever Lived, and lives."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "You are great Paul. A living legend of rock.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I still can't believe how good his voice sounds at 76!! Incredible!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"The oldest songs sound so fresh and so beautiful, simple and authentic. They sound like an eternal spring."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "THE MUSIC OF THE BEATLES / PAUL MC CARTNEY IS IMMORTAL!",
    "": "",
  },
  {
    ARTIST: "Queens of the Stone Age",
    LINK: "https://youtu.be/79yiz_Zb7fE",
    ID: "79yiz_Zb7fE",
    COMMENT: "epic!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"I agree, one of the best lineup."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/ExGw382UGZU",
    ID: "ExGw382UGZU",
    COMMENT:
      "Being a drummer in a QOTSA'S show is equivalent to running a marathon",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Better Living is such an under used and underrated jam",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Man! The sound of this gig is delicious!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Such a great performance, QOTSA one of the best live performers in the business"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "This version of better living is the best I’ve ever heard!!! Mad props",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "What a great show!! One of their best for sure!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "amazing performance as always !!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The definitive setlist!!!!  WOOOOOOOW",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "this is the best!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I had the pleasure to be there. Great gig!",
    "": "",
  },
  {
    ARTIST: "Pixies",
    LINK: "https://youtu.be/KsxNpBou1Ts",
    ID: "KsxNpBou1Ts",
    COMMENT: "Pixies is one of the best bands ever. It changed rock music.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Hell yes!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Long live to the KingS",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wowowo",
    "": "",
  },
  {
    ARTIST: "Imagine Dragons",
    LINK: "https://youtu.be/NapLxHp09DU",
    ID: "NapLxHp09DU",
    COMMENT: "The only band that is much better in live performances",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "It's great how happy he is with jumping and hopping around the podium",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "When his fans know the lyrics better than him xD",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "he's actually wearing a shirt what the heck",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I always wish you could perform Monster and Warriors, these two songs are gold to me ♥️"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I love Imagine Dragons soo much. The passion and love put into their songs, and the joy on their faces when they\'re on stage just makes me so happy."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I nearly cried from Dan Reynolds speech during Demons.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Don't we all wish we were a rockstar singer like dan",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"I swear, anyone could propose to me at an Imagine Dragons Concert and I\'d say yes."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I teared up when demons started",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/M96oleMSx-c",
    ID: "M96oleMSx-c",
    COMMENT:
      "only person in my school and my family that enjoy IMAGINE DRAGONS",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Best band ever!! I love how they don\'t put all kinds of trash and junk into their lyrics like everyone else. They are a one of a kind band, my personal favorite band ever."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Wow i was a casual imagine dragons fan before, just knowing their radio songs, but after seeing them performing live last thursday, i fel in love with them!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Dan is making me want to purchase everything he has ever made, what an amazing guy!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The happiness in Dan's face is like the best. Me da vida we",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Dan has the most adorable smile I have ever seen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The bass solo before ""Amsterdam"" is just amazing"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "IMAGINE DRAGONS DOMINATING THIS WORLD!!!❤",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I love Imagine Dragons so much that I seriously don't care whether they performed many songs from their new album or not. :)",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "My daughter is obssed with this band. She made it her goal to learn all the lyrics all there songs.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/Iz3ETf0Fqys",
    ID: "Iz3ETf0Fqys",
    COMMENT: "This guys never change IMAGINE DRAGONS NEVER CHANGE ♥️",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"best band ever, I love their songs they convey love and that\'s amazing ...."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "we always need to appreciate how amazing imagine dragons is live",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They are such a good band to see live!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I’m learning believer on my violin ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love imagine dragons",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Excelente simplemente increible!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'm still grateful for thunder",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "You are really amazing!!! Love you guys!!! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"great band, great direct"',
    "": "",
  },
  {
    ARTIST: "Bloc Party",
    LINK: "https://youtu.be/aaVnpfAqCXg",
    ID: "aaVnpfAqCXg",
    COMMENT: "kele needs to stop skipping leg day",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Kele.Singing indy is really great. And the music of the band has a creative idea to progress, there is something new to listen."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Different music,and member,this girl not bad at drummer,go Bloc Party"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Shoutout to everyone with me in the moshpit at the front",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing band.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "what a bangin set. awesome",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Shreded Kele is Shredding the guitar",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Masterpiece.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i have to admit that its actually a good performance...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "best!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/8nOsuuhQd1o",
    ID: "8nOsuuhQd1o",
    COMMENT: "Bloc party is a powerful band because of Matt Tong",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Idc what anyone says, Four was awesome"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Team A is so raw and pure, i love the energy of all four!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Awesome, but does anyone else feel as if almost every song is slightly out of control?"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Love it! Just hate that Kele doesn't sing the original lyrics for disappear here at the beginning of the song.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "wow amazing  ♥ ♥ ♫ 100% power",
    "": "",
  },
  {
    ARTIST: "Spoon",
    LINK: "https://youtu.be/NwB7Bi5dQF8",
    ID: "NwB7Bi5dQF8",
    COMMENT: "I love how Britt tries to fix his hair and just gives up.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Spoon is the best, every album is epic, and they just keep getting better"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"A band that has not only gotten better w age, but that can more than deliver every time live. Spoon are ace."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"every once in a while in my life, I listen to Gimme Fiction, it is one of my favorite albums evah mofos."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Goddamn that’s a good set.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"If you want rock n roll, this is just about as good as it gets."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the intro to do I have to talk you into it is great",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The bassline on don't you evah is so awesome. Still my favorite Spoon song.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"This hot show, especially Pink Up, blew me away. So many mesmorizing songs."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is overwhelmingly amazing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/0tdeWIIMHbA",
    ID: "0tdeWIIMHbA",
    COMMENT: "how does spoon always sound Exactly Correct",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I've seen spoon at least 12 times and never have i been anything less than amazed.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I don't know when but one day I will surely see you guys live. Awaiting that life changing moment.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "legends",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "awesome!",
    "": "",
  },
  {
    ARTIST: "1975",
    LINK: "https://youtu.be/5kiY87XLahk",
    ID: "5kiY87XLahk",
    COMMENT:
      "The 1975 is the band that i want to listen when the worlds is ending.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I am now cured of corona virus",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "this was one of the most iconic shows of the decade",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "T H E   1 9 7 5   Y O U ' R E   M Y   M E D I C I N E",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"George is a drum beast, such an underrated drummer, he doesn\'t need to play 200 bpm to be so good,god."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "this is the prettiest thing that i ever see",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "My boyfriend just broke up with me today and I’m just here to comfort myself. Thank you The 1975!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"How ironic that when Matty sings ""I\'m looking through you while you\'re looking through your phone"" a sea of phones can be seen in the audience."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"God, how i\'m fallin love too much with this music"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"man, that performance of ""the sound"" is absolutely mental."',
    "": "",
  },
  {
    ARTIST: "Police",
    LINK: "https://youtu.be/3RWbh9KKkdI",
    ID: "3RWbh9KKkdI",
    COMMENT: "I'm convinced stewart Copeland thinks his drums owe him money.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "God will people just start playing instruments again for the love of god.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Why do we spend billions on particle accelerators when science should just study Stewart Copeland's  drumsticks LOL",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "anyone who tries to say that Copeland isn't one of the greatest drummers ever to walk on this planet needs their head looking at",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Copeland in his prime was like TNT with drum sticks attached",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Stewart and his extreme attack , Andy\'s layed back chords and Stings Vocals and Bass are all absolutely Brilliant ."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the only concert that the band played entirely in their pajamas.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"What a band, what a DRUMMER....Stewart Copeland = god with a drumkit"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Nice to see no smartphones in the audience! :D",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Sting solo career was good....... but with The police he is a master with the masters stewart and Andy...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/F4VjsqR5Vbc",
    ID: "F4VjsqR5Vbc",
    COMMENT: "the hi-hat show: featuring The Police",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Stewart Copeland = Legend",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Copeland is just mesmerizing.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Stewart Copeland is absolutely awesome",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Drummer has some of the best percussion skills going, unreal"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Police: now with 40% more hi-hat...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "goddamn sting and that fretless bass on walking on the moon",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best drummer on the planet!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Walking on the moon. Damn. What a song!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the greatest bands ever.",
    "": "",
  },
  {
    ARTIST: "Radiohead",
    LINK: "https://youtu.be/C9_IhE5Xk0k",
    ID: "C9_IhE5Xk0k",
    COMMENT: "i love how radiohead is releasing all this stuff it's so cool",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "King of Limbs is the definition of underrated...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i will force my children to listen to this",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is a good show because Thom has a ponytail.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "they play in their own league... the most important band of the last 25 years...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Radiohead is an ancient treasure a moment of silence to the people that haven't heard them.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The end of Pyramid song is breath taking!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Thom dancing is so cool",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Why does Jonny's guitar sounds so low at most songs?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Toms voice is totally on it through this whole thing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/RjQZd8p-eBM",
    ID: "RjQZd8p-eBM",
    COMMENT:
      "Back when Thom looked like a KPop star instead of homeless old man",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Johnny Greenwood back when he was looking older.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "6 years later this band released Kid A",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "It feels so weird that the audience isn't singing along to Fake Plastic Trees",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"The ""My Iron Lung"" here is literally the recording used on the album. Fantastic stuff."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"There\'s something really special about ""Blow Out"""',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They had such a different energy back in early 90's",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Blow Out is really an excellent set closer.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Always weird seeing Phil with a wig",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is the most still i have ever seen Colin during a show",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/MuqDMOr_aLk",
    ID: "MuqDMOr_aLk",
    COMMENT: "one of the best radiohead shows ever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I am listening in the dark with a glass of wine.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Its 4 am and I stayed awake for this",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The National Anthem is always insanely amazing.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Finally i can watch Jigsaw Falling into Place live",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Best version of All I Need, hands down. Transcendental !"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Jigsaw Falling into Place",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best concert in my life!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the best Radiohead eras. Jonny's hair was fire.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "best show ever by far",
    "": "",
  },
  {
    ARTIST: "Alanis Morissette",
    LINK: "https://youtu.be/Y1RP0hXWgX0",
    ID: "Y1RP0hXWgX0",
    COMMENT: "she makes it difficult for the snipers",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She s Walked at least 20km",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The bassist is the most 1999 looking man I have ever seen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Alanis was the Janis Joplin of this Woodstock '99 edition",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Her voice is stunning. Just like it sounds on the albums.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Holy shit Alanis is good live. This set is off the charts good.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Alanis Morissette is a rock and roll goddess. Little pill was the soundtrack of the 90's and her and her band killed it at woodstock 99",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This woman's voice is incredible! She's special.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She is authentic.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Great Performance... Awful crowd.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/jIRmCrHFXBw",
    ID: "jIRmCrHFXBw",
    COMMENT:
      "\"How many of us love this woman? She's a music legend, she's an inspiration\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Ladies and gentlemen THE GODDESS OF ROCK. She is so powerful!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I still have the VHS in my cabinet",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is so iconic!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I Love THIS Era",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I can't describe what I feel with Alanis. It's so true.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing. When the world was just simply a better place.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of my favorite albums ever",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Blu Ray reissue please!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Thanks Alanis! we love u",
    "": "",
  },
  {
    ARTIST: "Phoenix",
    LINK: "https://youtu.be/STixAvSrnlc",
    ID: "STixAvSrnlc",
    COMMENT: "One of the most under appreciated bands in the history of music",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Phoenix should be headlining Coachella",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "drummer is god",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Kids better listening this band.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "THIS SETLIST IS GLORIOUS!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"The drummer is soooo on point, perfect performance!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Armistice is on a different level",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"so freaking amazing, this band is absolutely incredible and so underrated, and the drummer is a legend for sure!."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I could watch the drummer all day long........damnnnnn......",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "That synth line is absolutely dominating this performance on J-boy.",
    "": "",
  },
  {
    ARTIST: "Starsailor",
    LINK: "https://youtu.be/pOn3K86p--o",
    ID: "pOn3K86p--o",
    COMMENT:
      "Been a fan since MGS3 which feels like so long ago.... Love your music!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Love it!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Class!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Thank you for accompanying me from my junior years (2002) til this time. ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "First song heard from them is Four to the floor when I was at middle school.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Fabulous.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amo ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Man! Love it! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Love this band",
    "": "",
  },
  {
    ARTIST: "R.E.M.",
    LINK: "https://youtu.be/LuLH-Br7g0Q",
    ID: "LuLH-Br7g0Q",
    COMMENT: "Like the country one too.....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "We really needs these guys to start playing and writing again.  Such a void in music now.  They are way to good to stop playing.  Vacations over...lol",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amo !!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Your voice, heart, soul and eyes. WOW AGAIN AMAZING. just Julie"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amooooo!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The best i ever seen...thanks REM!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "most touching moment",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"WOW, IT LOOKS LIKE HE HAS TEARS. "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Me too. Love them !!!?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Wow love the use of the mandolin !",
    "": "",
  },
  {
    ARTIST: "St. Vincent",
    LINK: "https://youtu.be/UHjELj8FhD8",
    ID: "UHjELj8FhD8",
    COMMENT: "she is a baddas guitarrist.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"Annie is such a great guitarist. She has taken David Bowie's aesthetic, and built her own unique sound. It's such a privilege to listen to her work. \"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"Keep your eye's open people, she's going down in music history.\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Annie Clark is my queen.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She's so talented...one of the master of distortion guitar...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Fantastic, now she\'s in her Bowie stage! Somebody introduce her to Nine Inch Nails"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The guitar solo at the end of rattlesnake is freaking awesome!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The effect on the snare at the beginning reminds me of an AT-AT shooting!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of her best performances.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love this so much. Annie is such a genius. ",
    "": "",
  },
  {
    ARTIST: "Courtney Barnett",
    LINK: "https://youtu.be/xV_zbJ8SflU",
    ID: "xV_zbJ8SflU",
    COMMENT:
      "Neil Young was right. Rock and Roll can never die. What a refreshing sound! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Go Courtney!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She really is a true modern rock star.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "all bow before the Queen",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"I never really clicked with Hopefulessness until seeing Courtney live. Then I GOT it: it's a rock song, it's practically a Nirvana tune. Awesome talent.\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"So happy she added the keys to her live shows for the new record, makes the songs sound much fuller."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "her entire band is so lovable.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Im a little obsessed. Haven't heard something so classic but new since The White Stripes i'd say.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "god shes stupid hot the way she plays her guitar",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"This rocker can shred a freaking guitar, wow."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/ti8-z_ORI5U",
    ID: "ti8-z_ORI5U",
    COMMENT: "That is the correct hairstyle for Barcelona.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I can't believe she is the only guitarist in the group.  It  is such a full sound.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Courtney Barnett is my number one bucketlist concert.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Yea she is a fkin bad ass, speaks truth, rips left handed guitar perfect style-"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Courtney is so freakin rock n roll!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This was one of the BEST sets!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I'm into C.B.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Amazing artist!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "first time i see her playing at night lol",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "chicks with mullets <3",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/A3D6v-u67x4",
    ID: "A3D6v-u67x4",
    COMMENT: "She's pretty fricking cool. So unassuming and kick ass.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "She could be Paul McCartney's daughter.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"in this digital age she, unlike most of her contemporaries understands dynamics"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Damn her Sonic Youth's shirts so cool",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "So original and great guitar tones .... love her 70s hair!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "fabulous but listening here the bass is inaudible",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Great performance !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "sonic youth",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Courtney is so Awesome!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Sounds awesome despite not being able to hear the bass.",
    "": "",
  },
  {
    ARTIST: "Sonic Youth",
    LINK: "https://youtu.be/hUcShyAarjw",
    ID: "hUcShyAarjw",
    COMMENT: "you guys are incredible and a total inspiration",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I wanna be kicked by kim gordon",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "concert is AMAZING!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They’re still teens who love Sonic Youth",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Just imagine being allowed to express yourself!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"""Sonic Youth is playing next..."" "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Steve Shelley -so underrated",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Unforgettable concert! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Nice! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Sonic Youth Forever.",
    "": "",
  },
  {
    ARTIST: "Bastille",
    LINK: "https://youtu.be/nHHW-owvHdI",
    ID: "nHHW-owvHdI",
    COMMENT: "Woody throws a drumstick at Kyle",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I love Dan's bad dancing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "So jealous of the girl in Icarus that holds Dans hand",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "i just wanna cry dan's voice is stunning",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Has to be my favorite band",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "POMPEII never gets old",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Love this!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That moment you name your child Daniel....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "oh they became my favourite band right now",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Weight of Living",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/uiU06Jx0B3Q",
    ID: "uiU06Jx0B3Q",
    COMMENT:
      '"So, a band with a great album, doesn\'t lipsync, and talks to the crwod of fans live, whats not to love about them. "',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "\"If you don't think Dan is adorable, you're wrong\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "How can he sing and go up and down stairs at the same time. I can barely breath and go up the stairs.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "How does his voice  not shake when he jump?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "The security guy was so pissed when Dan climbed over  the pole during flaws",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Dan's dorky dancing gives me life",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "his dance moves reminds me of Lorde's dance moves ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Bastille is the best band in the freaking world okay",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Look at him dancing then getting embarrassed and stopping, so adorable"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"the dancing... haha dan is great, love the energy they all have"',
    "": "",
  },
  {
    ARTIST: "Sheryl Crow",
    LINK: "https://youtu.be/dWrrdxviU-w",
    ID: "dWrrdxviU-w",
    COMMENT: "those pants..",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Sheryl is an excellent musician and a great charismatic singer !! A complete artist! I adore her!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "\"Sheryl has a great voice, I love it, she's the best singer & musician, that's why I admire her!\"",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Her voice sounds great, and she\'s such a good musician."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "she's so GOOD",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Love Sheryl Crow. What's her drummers name. Love watching him. He's so full of energy",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Awesome concert.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Great Concert!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "OMG she is so hot!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "In love!!!! Lol",
    "": "",
  },
  {
    ARTIST: "Eric Clapton",
    LINK: "https://youtu.be/fqz2AhQsRWE",
    ID: "fqz2AhQsRWE",
    COMMENT: "Old slow hand Eric can still play a pretty mean guitar.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Clapton is still better than most guitarists with one hand tied behind his back! Best guitar player ever in my humble opinion!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Does anybody recognise what a good drummer Henri Spinetti is?",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Love the music though!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"subtle and masterful, like old wine."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Those back up singers are awesome!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Clapton and Page the greatest!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He's in such a good shape..",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Clapton is God'",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "its CLAPTON! its GOD!",
    "": "",
  },
  {
    ARTIST: "Chicago",
    LINK: "https://youtu.be/_oAoSZ2y1cw",
    ID: "_oAoSZ2y1cw",
    COMMENT:
      "Is anyone as obsessed with this concert as I am? It's led me to believe that Chicago is one of the top bands of all time.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Terry Kath was one of the best guitarists of all time.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"No pyro, no smoke machines, no big fancy light show...just a super talented band kicking ass for 90 minutes."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Terry Kath - sang like Ray Charles, played like Hendrix ."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "this is the greatest performance Ive ever seen in my life. How do such young people write such amaizing music.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"After watching this, I think Jimi Hendrix was right about Terry Kath!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"This was Terry\'s band, what a guitarist!!!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "WHAT ABOUT THE DRUMMER????? SO NATURAL AND COOL...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Terrys vocals on color my world are timeless",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is Chicago in their prime. So good...so damn good.",
    "": "",
  },
  {
    ARTIST: "Placebo",
    LINK: "https://youtu.be/NF5vr0owif8",
    ID: "NF5vr0owif8",
    COMMENT: '"I just realized, nobody is holding up a phone, for a change."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "One of the most underrated singer of all time! He sounds exactly like the studio version",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Brian Molko looks kind of like Uma Thurman in Pulp Fiction after the drug overdose here.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "They should really try and play some songs from their first two records. They're legendary.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "He looks like the king from Shrek with that hairdo",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Placebo are really incredible and sincere...Brian's manner of singing is unique.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"This is awesome, Placebo are like a fine wine"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That chick with flower headband",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"love placebe!great music and lyrics,much better than that comercial muse!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is always my go to Placebo concert when I need a fix.",
    "": "",
  },
  {
    ARTIST: "Aerosmith",
    LINK: "https://youtu.be/Gerf9gHEJoY",
    ID: "Gerf9gHEJoY",
    COMMENT: '"Joe Perry , the coolest guy in rock history."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "the fact that they play quite a few deep tracks and not just all their hits live shows how confident these guys are in all of their music",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Holy cupcakes!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"He must be the best LIVE SINGER in the world, his voice is perfect."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Steven Tyler is without a doubt the greatest frontman in rock history.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Hands in the air without cell phones... You gotta love it!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Everybody talks about Joe Perry, but can we please take a moment to note how Tom Hamilton is one of the coolest bassists ever?"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is what a PROFESSIONAL rock band looks like!!!!!   ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "These Boy's were on top of their game at this show!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the best band of all time!!!! they have it all!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "https://youtu.be/HSBOCnpLSV8",
    ID: "HSBOCnpLSV8",
    COMMENT: "Tyler and Perry coked to the gills.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Gotta be one of the ugliest stage designs I have ever seen.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I was so high I thought it sounded great",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Yikes.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The first Monsters Of Rock! ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "AC/DC smashed this event",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Nice hearing Reefer Headed Woman...kind of rare!  Great tune.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Mr Perry playing Stratocasters...yea Joe!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Ahhh, days on the green, thank you Bill Graham."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I hope the guy who oked this stage got fired.",
    "": "",
  },
  {
    ARTIST: "Iggy Pop",
    LINK: "https://youtu.be/HAgaCs5hruc",
    ID: "HAgaCs5hruc",
    COMMENT:
      "Iggy always brought along the best musicians. Pure skill everywhere. So enjoyable.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "The Grandfather of punk and still going strong.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "ITS GAVIN HARRISON ON DRUMS",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Iggy the voice!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Gavin Harrison plays the drums!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"its funny how most of the live stuff is Stooges,you never forget your first love."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Band NAILED this show !",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "his voice sounds amazing here!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "the igster is always good",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "iggerizzed!!!!",
    "": "",
  },
  {
    ARTIST: "Clash",
    LINK: "https://youtu.be/CLKl6FIBH0U",
    ID: "CLKl6FIBH0U",
    COMMENT:
      '"the drugs really kicked in at during jimmy jazz, and i\'m referring to myself and not joe"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Mick Jones  unsung hero of the clash",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Bruce Springsteen wishes he was Joe Strummer",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Best Punk Band...In my opinion. Joe is just great.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "only band that matters",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Joe Strummer...maybe the best frontman I've seen.  And there are so many great ones.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Jones is brilliant on Spanish Bombs",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is a 5 star Clash concert",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Complete Control what a song!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "A fantastic performance by a great band at the peak of their powers.",
    "": "",
  },
  {
    ARTIST: "Ramones",
    LINK: "https://youtu.be/Sp3zaeOyL7Q",
    ID: "Sp3zaeOyL7Q",
    COMMENT: "And every kid in that crowd went home and started a band.....",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is absolutely one of the best recorded live concerts ever.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: '"Ramones didn\'t have a style, they were the style"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"how tf does joey breathe throughout without a break, what a king omg"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Johnny is way underrated, even among Ramones fans. Arguably the best rhythm guitarist of all time."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is what it feels like to go through a blender.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Mind blowing, these guys didn\'t give a shit and built their own universe, epic."',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "Best live album of all times from any artists known to mankind!!!!!!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is a treasure.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the most powerful live performances  ever...",
    "": "",
  },
  {
    ARTIST: "Duran Duran",
    LINK: "https://youtu.be/T4dKTblXrF4",
    ID: "T4dKTblXrF4",
    COMMENT:
      "Most bands have a lead guitarist ... Duran Duran had a lead Bassist!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This is GOLDEN",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "John Taylor on top of his game! Dig that bassline...",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"right out of the gate, Duran Duran\'s bassist is phenomenal...I never realized! Wow!"',
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "They single handedly kept the white pants industry alive!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Outstanding! The Taylor's are all full throttle.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "That bass is legit",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I've always loved the bass on New Religion; absolutely funky and fabulous!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "John Taylor and that bass.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "This band has a lot of future potential.",
    "": "",
  },
  {
    ARTIST: "Fall Out Boy",
    LINK: "https://youtu.be/-3LfOi2EfHE",
    ID: "-3LfOi2EfHE",
    COMMENT: "this audience is why MCR wrote a song about teenagers",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I can't believe people don't know who Fall Out Boy is.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Andy has a nice shirt there.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "fall out boy will be the death of me.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I AM DISAPPOINTED IN THE CROWD ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "I love how Patrick and Pete just skip around! It is so dang cute!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Patrick is just the sweetest thing",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Joe's hair is bigger than my future ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Pete is a spooky scary skeleton",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "it was so cute when Patrick skipped across the stage omg",
    "": "",
  },
  {
    ARTIST: "Grouplove",
    LINK: "https://youtu.be/ky3uVoQeK8U",
    ID: "ky3uVoQeK8U",
    COMMENT: "Absolutely love Hannah's energy.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "One of the best live bands you'll hear these days. Pure energy",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "There drummer is so sick ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "love how much heart they put into the performance.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "There drummer looks like an older Nat Wolff",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "xD I love the drummers faces ",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      "everyone with there face in their phone doesnt deserve to be there.",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "Huge crush on Hannah",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT: "I simply love this group!!",
    "": "",
  },
  {
    ARTIST: "",
    LINK: "",
    ID: "",
    COMMENT:
      '"Just wow amazing haha, so much energy and emotion put into their work."',
    "": "",
  },
];

module.exports = red;
